FORMAT: 1A
HOST: http://funhub-devel.gunet.gr/

# SSN API (amka-services)
## About this API
This API provides a resource to view, manage and validate information
about SSN (AMKA) numbers and their related metadata.

# Home [/]
This is the home resource.

## API Discovery [GET]
* Request (application/vnd.siren+json)
* Response 200 (application/vnd.siren+json)

        {
          "entities": [
            {
              "href": "...",
              "rel": [
                "ssn"
              ]
            }
          ],
          "actions": [
            {
              "name": "ssn",
              "href": "...",
              "method": "GET",
              "fields": [
                {
                  "name": "birthDate",
                  "type": "date"
                },
                {
                  "name": "familyName",
                  "type": "text"
                },
                {
                  "name": "ssn",
                  "type": "text"
                }
              ]
            }
          ],
          "links": [
            {
              "rel": [
                "self",
                "index"
              ],
              "href": "..."
            }
          ]
        }


# Group SSN resources

# SSN Collection [/ssn/{?familyName,birthDate,ssn}]
## Validation [GET]
+ Parameters
    + familyName: `Παπαδόπουλος` (text, optional) - surname or family name to validate with.
    + birthDate: `1981-05-10` (date, optional) - birth date in ISO 8061 format.
    + ssn: `12093134234` (text) - the SSN to validate with
+ Response 200 (application/vnd.siren+json)

        { "entities": [] }

+ Response 404